#!/bin/bash

# Repeatedly call the recognise number script
#
# Example usage:
# ./recognise_all_numbers ../../Resources/NumberRecognition/*deg.jpg
#

script_directory=`dirname $0`

if [[ "$#" -eq 0 ]]; then
  echo "recognise_all_numbers: At least one file must be supplied!"
  exit 1
fi

for i in "$@"
do
  echo `basename $i .jpg`
  $script_directory/recognise_number.py $i || { echo ERROR: recognise_number.py failed; exit 1; }
done
